/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package figuras_examen;

/**
 *
 * @author guich
 */
public class Ventana extends javax.swing.JFrame {
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cuadrado = new javax.swing.JButton();
        Reactangulo = new javax.swing.JButton();
        Triangulo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Calcularboton = new javax.swing.JButton();
        Cualado = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        ladoder = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ladoizq = new javax.swing.JTextPane();
        Trianbase = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        Perimetrocir = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Areacir = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        Radiocirc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Circulo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Perimetrotria = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Areatria = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        Hipotenusatria = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Perimetrorect = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Arearect = new javax.swing.JTextPane();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Areacua = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Perimetrocua = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Alturatria = new javax.swing.JTextField();
        Alturabase = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Rectbase = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tipotriangulo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("interfaz");
        setBackground(new java.awt.Color(40, 238, 89));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        Cuadrado.setBackground(new java.awt.Color(250, 250, 210));
        Cuadrado.setText("Cuadrado");
        Cuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CuadradoMouseClicked(evt);
            }
        });
        Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadradoActionPerformed(evt);
            }
        });
        getContentPane().add(Cuadrado);
        Cuadrado.setBounds(123, 96, 94, 23);

        Reactangulo.setBackground(new java.awt.Color(250, 250, 210));
        Reactangulo.setText("Rectangulo");
        Reactangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReactanguloActionPerformed(evt);
            }
        });
        getContentPane().add(Reactangulo);
        Reactangulo.setBounds(540, 96, 90, 23);

        Triangulo.setBackground(new java.awt.Color(250, 250, 210));
        Triangulo.setText("Triángulo");
        getContentPane().add(Triangulo);
        Triangulo.setBounds(736, 96, 90, 23);

        jLabel3.setText("Ingresa lado:");
        jLabel3.setAlignmentX(0.5F);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(129, 125, 100, 16);

        jLabel4.setText("Ingresa base:");
        jLabel4.setAlignmentX(0.5F);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(546, 125, 90, 16);

        jLabel7.setText("Ingresa base:");
        jLabel7.setAlignmentX(0.5F);
        jLabel7.setAlignmentY(1.0F);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(687, 125, 80, 16);

        Calcularboton.setBackground(new java.awt.Color(255, 204, 51));
        Calcularboton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Calcularboton.setText("Calcular");
        Calcularboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularbotonActionPerformed(evt);
            }
        });
        getContentPane().add(Calcularboton);
        Calcularboton.setBounds(435, 474, 179, 56);

        Cualado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CualadoActionPerformed(evt);
            }
        });
        getContentPane().add(Cualado);
        Cualado.setBounds(123, 147, 94, 30);

        jScrollPane7.setViewportView(ladoder);

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(789, 210, 146, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setText("Ingresa medida lado derecho:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(789, 187, 146, 14);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        jLabel1.setText("Elige figura:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setText("Ingresa medida lado izquierdo:");

        jScrollPane8.setViewportView(ladoizq);

        Trianbase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrianbaseActionPerformed(evt);
            }
        });

        jScrollPane10.setViewportView(Perimetrocir);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel18.setText("  Perimetro circulo");

        jScrollPane9.setViewportView(Areacir);

        jLabel17.setText("     Area circulo");

        Radiocirc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiocircActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingresa radio:");
        jLabel6.setAlignmentX(0.5F);

        Circulo.setBackground(new java.awt.Color(250, 250, 210));
        Circulo.setText("Circulo");
        Circulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CirculoMouseClicked(evt);
            }
        });

        jScrollPane5.setViewportView(Perimetrotria);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setText("Perimetro triángulo");

        jScrollPane6.setViewportView(Areatria);

        jLabel10.setText("Area triángulo");

        Hipotenusatria.setAutoscrolls(false);
        Hipotenusatria.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane11.setViewportView(Hipotenusatria);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel19.setText("      Hipotenusa");

        jScrollPane4.setViewportView(Perimetrorect);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setText("Perimetro rectangulo");

        jScrollPane3.setViewportView(Arearect);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("Perimetro cuadrado");

        jScrollPane1.setViewportView(Areacua);

        jLabel9.setText("Area cuadrado");

        jScrollPane2.setViewportView(Perimetrocua);

        jLabel11.setText("Area rectangulo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CALCULADORA DE FIGURAS");

        jLabel8.setText("Ingresa altura:");
        jLabel8.setAlignmentX(0.5F);

        Alturatria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturatriaActionPerformed(evt);
            }
        });

        Alturabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturabaseActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingresa altura:");
        jLabel5.setAlignmentX(0.5F);

        Rectbase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectbaseActionPerformed(evt);
            }
        });

        jLabel20.setText("   Tipo:");

        jScrollPane13.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane13.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        tipotriangulo.setColumns(20);
        tipotriangulo.setRows(5);
        jScrollPane13.setViewportView(tipotriangulo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(473, 473, 473))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radiocirc, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane9)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Alturabase, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rectbase, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(54, 54, 54)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Trianbase, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Alturatria, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(Circulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Radiocirc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Rectbase, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Trianbase, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Alturatria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Alturabase, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                                .addComponent(jScrollPane9))
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                            .addComponent(jScrollPane4)
                                            .addComponent(jScrollPane5)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(312, 312, 312))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadradoActionPerformed

    private void CalcularbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularbotonActionPerformed
        double ladocua, baserect, alturarect, radiocirc,basetria, alturatria, hipotenusa=0, lado1tria, lado2tria;
        String tipotria;
        double arearect, areacua, areatria, areacirc;
        double perimetrorect, perimetrocua, perimetrocirc, perimetrotria;
        ladocua=Double.parseDouble(Cualado.getText());
        baserect=Double.parseDouble(Rectbase.getText());
        alturarect=Double.parseDouble(Alturabase.getText());
        radiocirc=Double.parseDouble(Radiocirc.getText());
        basetria=Double.parseDouble(Trianbase.getText());
        alturatria=Double.parseDouble(Alturatria.getText());
        lado1tria=Double.parseDouble(ladoizq.getText());
        lado2tria=Double.parseDouble(ladoder.getText());
        
        arearect=baserect*alturarect;
        perimetrorect=(baserect*2)+(alturarect*2);
        Arearect.setText(" "+arearect);
        Perimetrorect.setText(" "+perimetrorect);
        
        areacua=ladocua*ladocua;
        perimetrocua=ladocua*4;
        Areacua.setText(" "+areacua);
        Perimetrocua.setText(" "+perimetrocua);
        
        areacirc= 3.1416*(radiocirc*radiocirc);
        perimetrocirc= 3.1416*(radiocirc+radiocirc);
        Perimetrocir.setText(" "+perimetrocirc);
        Areacir.setText(" "+areacirc);
        
        areatria=(basetria*alturatria)/2;
        hipotenusa=Math.sqrt(Math.pow(alturatria,2)+Math.pow(basetria,2));
        perimetrotria=basetria+lado1tria+lado2tria;
        Areatria.setText(" "+areatria);
        Perimetrotria.setText(" "+perimetrotria);
        Hipotenusatria.setText(" "+hipotenusa);
        
        if (lado1tria==basetria && lado2tria==lado1tria && lado2tria==basetria){
            tipotria ="Equilatero";
            tipotriangulo.setText(" "+tipotria);
        }else if(basetria!=lado2tria && basetria!=lado1tria && lado1tria!=lado2tria) {
            tipotria ="Escaleno";
            tipotriangulo.setText(" "+tipotria);
        }else{
            tipotria="Isoceles";
            tipotriangulo.setText(" "+tipotria);
        }
        
    }//GEN-LAST:event_CalcularbotonActionPerformed

    private void CualadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CualadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CualadoActionPerformed

    private void RectbaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectbaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RectbaseActionPerformed

    private void RadiocircActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiocircActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadiocircActionPerformed

    private void TrianbaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrianbaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrianbaseActionPerformed

    private void AlturabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturabaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturabaseActionPerformed

    private void AlturatriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturatriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturatriaActionPerformed

    private void ReactanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReactanguloActionPerformed
        Figuras.Cuadrado(jPanel1.getGraphics(),420,100, 100, 60);
    }//GEN-LAST:event_ReactanguloActionPerformed

    private void CuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuadradoMouseClicked
        Figuras.Cuadrado(jPanel1.getGraphics(),145,190, 60, 60);
    }//GEN-LAST:event_CuadradoMouseClicked

    private void CirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CirculoMouseClicked
        Figuras.Circulo(jPanel1.getGraphics(), 310, 190, 100, 100);
    }//GEN-LAST:event_CirculoMouseClicked

    //private static Scanner leer = new Scanner(System.in);
    //private static Scanner leer1 = new Scanner(System.in);
    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alturabase;
    private javax.swing.JTextField Alturatria;
    private javax.swing.JTextPane Areacir;
    private javax.swing.JTextPane Areacua;
    private javax.swing.JTextPane Arearect;
    private javax.swing.JTextPane Areatria;
    private javax.swing.JButton Calcularboton;
    private javax.swing.JButton Circulo;
    private javax.swing.JButton Cuadrado;
    private javax.swing.JTextField Cualado;
    private javax.swing.JTextPane Hipotenusatria;
    private javax.swing.JTextPane Perimetrocir;
    private javax.swing.JTextPane Perimetrocua;
    private javax.swing.JTextPane Perimetrorect;
    private javax.swing.JTextPane Perimetrotria;
    private javax.swing.JTextField Radiocirc;
    private javax.swing.JButton Reactangulo;
    private javax.swing.JTextField Rectbase;
    private javax.swing.JTextField Trianbase;
    private javax.swing.JButton Triangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane ladoder;
    private javax.swing.JTextPane ladoizq;
    private javax.swing.JTextArea tipotriangulo;
    // End of variables declaration//GEN-END:variables
}
